# Following unit-test runs on OS Ubuntu.
# Arduino will be running on Ubuntu system and will be using two
# compilers "gnu, clang".

name: Arduino CI

on: [push, pull_request]

jobs:
  run-unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        compiler: [gnu, clang]

        include:
          - os: ubuntu-18.04
            nproc: "-j$(nproc)"
            mkdir_force: -p

          - compiler: gnu
            cc: gcc-9
            cxx: g++-9

          - compiler: clang
            cc: clang-9
            cxx: clang++-9

    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
      build_dir: build

    steps:
      - uses: actions/checkout@v2
      - name: Get dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y ${{ matrix.cc }}
          sudo apt-get install -y ${{ matrix.cxx }}
      - name: Create unit test build directory
        run: mkdir ${{ matrix.mkdir_force }} ${{ env.build_dir }}
      - name: Configure unit tests
        run: cd ${{ env.build_dir }} && cmake ..
      - name: Build unit tests
        run: cmake --build ${{ env.build_dir }} -- ${{ matrix.nproc }}
      - name: Run unit tests
        run: cd ${{ env.build_dir }} && ctest