name: GUI CI

on: [push, pull_request]

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Build App
        run: |
          cd UI
          bash ./gradlew build --stacktrace
  run-unit-tests:
      runs-on: ubuntu-latest
      steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
         java-version: 1.8
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Run unit tests
        run: |
          cd UI
          bash ./gradlew test --info
  run-instumented-tests:
      runs-on: ubuntu-latest
      steps:
      - name: "Build Android project"
        uses: vgaidarji/android-github-actions-build@v1.0.1
         
        with:
          args: "./gradlew connectedAndroidTest"
